export const HOBBY_LIST: string[] = [
  "Reading",
  "Writing",
  "Journaling",
  "Drawing",
  "Painting",
  "Sketching",
  "Calligraphy",
  "Origami",
  "Photography",
  "Videography",
  "Filmmaking",
  "Cooking",
  "Baking",
  "Grilling",
  "Fermenting",
  "Wine tasting",
  "Beer brewing",
  "Coffee roasting",
  "Tea ceremony",
  "Mixology",
  "Gardening",
  "Landscaping",
  "Bonsai",
  "Flower arranging",
  "Beekeeping",
  "Fishing",
  "Fly fishing",
  "Hunting",
  "Camping",
  "Backpacking",
  "Hiking",
  "Mountaineering",
  "Rock climbing",
  "Bouldering",
  "Caving",
  "Kayaking",
  "Canoeing",
  "Rafting",
  "Sailing",
  "Boating",
  "Surfing",
  "Paddleboarding",
  "Swimming",
  "Scuba diving",
  "Snorkeling",
  "Freediving",
  "Skiing",
  "Snowboarding",
  "Ice skating",
  "Sledding",
  "Snowshoeing",
  "Cycling",
  "Mountain biking",
  "BMX",
  "Skateboarding",
  "Rollerblading",
  "Running",
  "Jogging",
  "Trail running",
  "Marathon training",
  "Yoga",
  "Pilates",
  "Meditation",
  "Tai chi",
  "Martial arts",
  "Boxing",
  "Kickboxing",
  "Wrestling",
  "Fencing",
  "Archery",
  "Shooting sports",
  "Darts",
  "Billiards",
  "Bowling",
  "Golf",
  "Disc golf",
  "Tennis",
  "Table tennis",
  "Badminton",
  "Squash",
  "Racquetball",
  "Pickleball",
  "Basketball",
  "Volleyball",
  "Beach volleyball",
  "Soccer",
  "Football",
  "Baseball",
  "Softball",
  "Cricket",
  "Rugby",
  "Hockey",
  "Ice hockey",
  "Lacrosse",
  "Handball",
  "Gymnastics",
  "Cheerleading",
  "Dance",
  "Ballet",
  "Ballroom dancing",
  "Salsa dancing",
  "Swing dancing",
  "Line dancing",
  "Breakdancing",
  "Pole dancing",
  "Singing",
  "Choir",
  "Karaoke",
  "Playing guitar",
  "Playing piano",
  "Playing violin",
  "Playing drums",
  "Playing ukulele",
  "Playing bass",
  "Playing saxophone",
  "Playing trumpet",
  "Music production",
  "DJing",
  "Songwriting",
  "Composing music",
  "Podcasting",
  "Blogging",
  "Vlogging",
  "Acting",
  "Theater",
  "Improv comedy",
  "Stand-up comedy",
  "Puppetry",
  "Magic tricks",
  "Juggling",
  "Circus arts",
  "Sewing",
  "Knitting",
  "Crocheting",
  "Embroidery",
  "Quilting",
  "Weaving",
  "Spinning yarn",
  "Cross-stitch",
  "Macrame",
  "Jewelry making",
  "Beading",
  "Woodworking",
  "Carpentry",
  "Furniture building",
  "Wood carving",
  "Whittling",
  "Metalworking",
  "Blacksmithing",
  "Welding",
  "Pottery",
  "Ceramics",
  "Sculpting",
  "Glassblowing",
  "Stained glass",
  "Leatherworking",
  "Candle making",
  "Soap making",
  "Perfume making",
  "Model building",
  "Model trains",
  "Model airplanes",
  "Model cars",
  "Miniature painting",
  "Diorama building",
  "LEGO building",
  "3D printing",
  "Robotics",
  "Electronics",
  "Circuit building",
  "Ham radio",
  "Coding",
  "App development",
  "Web design",
  "Game development",
  "Board games",
  "Card games",
  "Chess",
  "Checkers",
  "Backgammon",
  "Poker",
  "Bridge",
  "Mahjong",
  "Dungeons and Dragons",
  "Tabletop RPGs",
  "Video gaming",
  "Esports",
  "Puzzle solving",
  "Jigsaw puzzles",
  "Crossword puzzles",
  "Sudoku",
  "Escape rooms",
  "Geocaching",
  "Bird watching",
  "Stargazing",
  "Astronomy",
  "Astrophotography",
  "Rock collecting",
  "Fossil hunting",
  "Metal detecting",
  "Antiquing",
  "Collecting stamps",
  "Collecting coins",
  "Collecting vinyl records",
  "Collecting comic books",
  "Collecting action figures",
  "Genealogy",
  "Language learning",
  "Traveling",
  "Road tripping",
  "Volunteering",
  "Foraging",
  "Whittling knives",
  "Car restoration",
  "Motorcycle riding",
  "Drone flying",
  "Kite flying",
  "Paragliding",
  "Skydiving",
  "Horseback riding",
  "Falconry",
  "Dog training",
  "Aquarium keeping",
  "Terrarium building",
  "Houseplant care",
  "Wine collecting",
  "Cigar tasting",
  "Barbecuing",
  "Smoking meats",
  "Cake decorating",
  "Bread making",
  "Cheese making",
  "Pickling",
  "Canning",
  "Home brewing cider",
  "Whiskey tasting",
  "Cocktail crafting",
  "Butchery",
  "Charcuterie",
  "Sushi making",
  "Pasta making",
  "Chocolate making",
  "Ice cream making",
  "Urban farming",
  "Vermicomposting",
  "Hydroponics",
  "Xeriscaping",
  "Topiary",
  "Herbalism",
  "Mushroom foraging",
  "Wild edible foraging",
  "Trapping",
  "Bowhunting",
  "Skeet shooting",
  "Paintball",
  "Airsoft",
  "Laser tag",
  "Parkour",
  "Freerunning",
  "Slacklining",
  "Aerial silks",
  "Pole fitness",
  "CrossFit",
  "Weightlifting",
  "Powerlifting",
  "Bodybuilding",
  "Calisthenics",
  "Stretching",
  "Foam rolling",
  "Barre",
  "Zumba",
  "Hula hooping",
  "Jump rope",
  "Trampolining",
  "Diving",
  "Water polo",
  "Rowing",
  "Crew",
  "Stand-up paddleboarding racing",
  "Windsurfing",
  "Kitesurfing",
  "Wakeboarding",
  "Water skiing",
  "Jet skiing",
  "White water rafting",
  "Canyoning",
  "Via ferrata",
  "Ice climbing",
  "Alpine skiing",
  "Cross-country skiing",
  "Ski jumping",
  "Luge",
  "Bobsledding",
  "Curling",
  "Speed skating",
  "Figure skating",
  "Synchronized swimming",
  "Platform diving",
  "Triathlon training",
  "Duathlon training",
  "Adventure racing",
  "Orienteering",
  "Letterboxing",
  "Treasure hunting",
  "Urban exploration",
  "Ghost hunting",
  "Storm chasing",
  "Cloud spotting",
  "Weather tracking",
  "Amateur astronomy",
  "Telescope building",
  "Radio controlled cars",
  "Radio controlled planes",
  "Radio controlled boats",
  "Slot car racing",
  "Go-karting",
  "Drag racing",
  "Autocross",
  "Car detailing",
  "Vintage car collecting",
  "Motorcycle restoration",
  "Bicycle restoration",
  "Skateboard building",
  "Longboarding",
  "Snowmobiling",
  "ATV riding",
  "Off-roading",
  "Overlanding",
  "Van life",
  "RV camping",
  "Tent camping",
  "Hammock camping",
  "Bushcraft",
  "Survivalism",
  "Wilderness first aid",
  "Knot tying",
  "Whittling spoons",
  "Blacksmith knife making",
  "Axe throwing",
  "Knife throwing",
  "Tomahawk throwing",
  "Slingshot shooting",
  "Frisbee",
  "Ultimate frisbee",
  "Kickball",
  "Kubb",
  "Cornhole",
  "Bocce ball",
  "Croquet",
  "Horseshoes",
  "Shuffleboard",
  "Foosball",
  "Air hockey",
  "Ping pong",
  "Mini golf",
  "Bowling league",
  "Trivia nights",
  "Pub quiz",
  "Book clubs",
  "Writing clubs",
  "Poetry",
  "Spoken word",
  "Screenwriting",
  "Playwriting",
  "Novel writing",
  "Short story writing",
  "Fan fiction writing",
  "Comic book creation",
  "Graphic novel making",
  "Cartooning",
  "Digital art",
  "Pixel art",
  "Animation",
  "Stop motion animation",
  "3D modeling",
  "Character design",
  "Concept art",
  "Tattoo design",
  "Body painting",
  "Face painting",
  "Henna art",
  "Nail art",
  "Hairstyling",
  "Makeup artistry",
  "Cosplay",
  "Costume making",
  "Prop making",
  "Wargaming miniature painting",
  "Wargaming",
  "Historical reenactment",
  "Renaissance faires",
  "Medieval combat",
  "Historical fencing",
  "Traditional archery",
  "Falconry training",
  "Pigeon racing",
  "Chicken keeping",
  "Rabbit breeding",
  "Reptile keeping",
  "Fish breeding",
  "Coral reef keeping",
  "Insect collecting",
  "Butterfly gardening",
  "Composting",
  "Seed saving",
  "Permaculture",
  "Urban beekeeping",
  "Winemaking",
  "Cider pressing",
  "Maple syrup tapping",
  "Sugaring",
  "Sourdough baking",
  "Fermented foods",
  "Kombucha brewing",
  "Kimchi making",
  "Distilling",
  "Cigar rolling",
  "Pipe smoking",
  "Coin flipping games",
  "Magic card collecting",
  "Trading card games",
  "Miniature railway operation",
  "Diecast car collecting",
  "Vintage toy collecting",
  "Antique furniture restoration",
  "Clockmaking",
  "Watchmaking",
  "Typewriter collecting",
  "Cassette tape collecting",
  "Retro gaming",
  "Arcade machine collecting",
  "Pinball",
  "Home theater building",
  "Amateur radio operation",
  "Drone racing",
  "Kite building",
  "Balloon twisting",
  "Card tricks",
  "Mentalism",
  "Escape artistry",
  "Sword swallowing",
  "Fire spinning",
  "Fire breathing",
  "Poi spinning",
  "Flow arts",
  "Contact juggling",
  "Diabolo",
  "Yo-yoing",
  "Whip cracking",
  "Lassoing",
  "Rodeo riding",
  "Bull riding",
  "Barrel racing",
  "Polo",
  "Equestrian dressage",
  "Show jumping",
  "Carriage driving",
  "Sled dog racing",
  "Dog agility",
  "Dog sports",
  "Cat shows",
  "Bird showing",
  "Pigeon fancying",
  "Scrapbooking",
  "Card making",
  "Calligraphy pens collecting",
  "Stationery collecting",
  "Bullet journaling",
  "Planner decorating",
  "Washi tape crafting",
  "Resin art",
  "Epoxy crafting",
  "Diamond painting",
  "Paint by numbers",
  "Adult coloring books",
  "Rug making",
  "Rug hooking",
  "Tapestry weaving",
  "Basket weaving",
  "Chair caning",
  "Furniture upholstery",
  "Cabinet making",
  "Wood turning",
  "Wood burning (pyrography)",
  "Marquetry",
  "Intarsia",
  "Taxidermy",
  "Bone carving",
  "Antler carving",
  "Gem cutting",
  "Lapidary",
  "Rock tumbling",
  "Mineral collecting",
  "Amateur geology",
  "Cave diving",
  "Wreck diving",
  "Spearfishing",
  "Ice fishing",
  "Noodling",
  "Crabbing",
];
